name: Build and Deploy Kanap Project

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install back end dependencies
        run: npm install
        working-directory: ./back
        # Assuming you have a similar structure for the back end

      - name: Start back end server
        run: nohup node server > /dev/null 2>&1 &
        working-directory: ./back
        # Modify as needed to match your server start command and directory structure

      - name: Install front end dependencies
        run: npm install
        working-directory: ./front
        # This ensures npm install is run in the correct directory

      # Optional: Build front end (if required by your project)
      # - name: Build front end
      #   run: npm run build
      #   working-directory: ./front
      # Uncomment and modify if your front end requires a build step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/html
